// <auto-generated />
namespace TP1_Module6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArtMartials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtMartials));
        
        string IMigrationMetadata.Id
        {
            get { return "202104280921316_ArtMartials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
